
#ifndef _OEM_SMEM_H_
#define _OEM_SMEM_H_

  SMEM_OTP_DATA_NV_DATA_CURRENTLY,
  SMEM_OTP_DATA_FROM_DT_OR_DIAG,
  SMEM_QISDA_DIAGPKT_REQ_RSP,
  SMEM_CHICAGO_HW_INFO,
  SMEM_USER_PARTITION_TBL = 109,

#endif
