#ifndef SMEM_PC_OEM_CMD_H
#define SMEM_PC_OEM_CMD_H

typedef enum
{
SMEM_PC_OEM_FIRST_GEN_CMD = 0,
SMEM_PC_OEM_CHECK_VERSION = SMEM_PC_OEM_FIRST_GEN_CMD,
SMEM_PC_OEM_AUD_LB_MIC1_TO_SPEAKER_START,
SMEM_PC_OEM_AUD_LB_MIC1_TO_SPEAKER_STOP,  
SMEM_PC_OEM_AUD_LB_MIC2_TO_HEADSET_START,
SMEM_PC_OEM_AUD_LB_MIC2_TO_HEADSET_STOP,  
SMEM_PC_OEM_AUD_ADIE_READ,
SMEM_PC_OEM_AUD_ADIE_WRITE,
SMEM_PC_OEM_SET_MODEM_MPU_PROTECTION,
SMEM_PC_OEM_VIBRATOR_CTRL,
SMEM_PC_OEM_PWRKEY_STATUS,
SMEM_PC_OEM_AC_WALL_READ_VOLTAGE,
SMEM_PC_OEM_USB_WALL_READ_VOLTAGE,
SMEM_PC_OEM_LAST_GEN_CMD = 100,	
SMEM_PC_OEM_FIRST_DT_CMD = 101,
SMEM_PC_OEM_FLASH_LED_ON = SMEM_PC_OEM_FIRST_DT_CMD,
SMEM_PC_OEM_FLASH_LED_OFF,

SMEM_PC_OEM_MAX_CMDS = 65535
}smem_pc_oem_cmd_type;
#endif

